apiVersion: apps/v1
kind: Deployment
metadata:
  name: suri-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: suri-pod
	  image: surendra548/test-java-proj:7
   	  ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: suri-service
spec:
  type: NodePort
  selector:
    env: prod
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 80
